
networks:
  seshat-network:
    external: false

services:
  seshat:
    image: codeberg.org/forgejo/forgejo:8.0.3-arm64-rootless
    container_name: seshat
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - seshat-network
    volumes:
      - ./seshat:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
      - '2222:22'
