networks:
  abzu:

services:
  seshat:
    image: codeberg.org/forgejo/forgejo:8
    container_name: seshat
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - abzu
    volumes:
      - ./seshat:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
      - '222:22'
